### ISSUE TITLE
Import in VirtualBox

### ISSUE THREAD

**Issue by TerrorSource** [AlexanderWillner/runMacOSinVirtualBox#63] opened 2019-03-21 09:54 UTC
Hi,

I want to have the VDI created by the script directly in VirtualBox but i cannot get it to work properly.
When i create a new VM in VirtualBox and select the VDI as hdd it will not boot.
I've edited this in the VM:
Floppy: disabled
Memory: 4096
Processor: 2
Video Memory: 128mb
USB: USB 3.0 controller

Does anyone has an idea how i get this working?
now i need to run "sudo sh runMojaveVirtualbox.sh run" each time i want to start it.

**Comment by AlexanderWillner** [comment] 2019-03-21 21:50
Hi,

the details how the VM is generated by the script can be seen at https://github.com/AlexanderWillner/runMacOSinVirtualBox/blob/238ba21b9d0b3f1eb31c42af737b5039000cf8ab/runMojaveVirtualbox.sh#L320

No need to use sudo to run the script with the parameter ```run```.

You also can just start the VM in the VirtualBox GUI, as the VM should be visible there. The script is just setting up everything once. Afterwards you could also delete it.

**Comment by coolidm** [comment] 2019-04-05 12:27
I also can't see the VM listed in virtual box or create a new one with the VDI. I would like to modify some settings on the config, but cant find the actual file.

**Comment by AlexanderWillner** [comment] 2019-04-06 17:12
The default folder is:
https://github.com/AlexanderWillner/runMacOSinVirtualBox/blob/238ba21b9d0b3f1eb31c42af737b5039000cf8ab/runMojaveVirtualbox.sh#L23

It should look like this:
<img width="952" alt="Screenshot 2019-04-06 at 19 11 01" src="https://user-images.githubusercontent.com/307605/55672817-cc2c2400-589f-11e9-98e7-ef7402277004.png">

Not sure why you're not seeing the VM. Where are your others stored?

**Comment by coolidm** [comment] 2019-04-07 16:49
It is not listed even when using "vboxmanage list vms", however I am still able to launch using the make process. Trying to register the vdi file shows an error "VBoxManage: error: Extra content at the end of the document. "

Is this the same issue as listed or should I create a new one?

**Comment by HigH-HawK** [comment] 2019-04-09 08:28
I'm having the same issue as coolidm and noticed something which may be the cause of the VM not showing up in the list.

All manual setup VMs in VirtualBox are stored under `/Users/your.username/VirtualBox VMs` but the script moves the required `.vbox` to `/var/root/VirtualBox VMs`. This could however be caused by running `make all` with `sudo` but I am not sure of this yet.

On the other hand you have to run it as `sudo` because you get an error if you are not doing so.

**Comment by AlexanderWillner** [comment] 2019-04-09 13:17
@HigH-HawK this could actually be the issue. @coolidm / @TerrorSource : can you verify? In that case we've to check in which case the root home is used (and not the user home)...

**Comment by HigH-HawK** [comment] 2019-04-10 13:52
@AlexanderWillner I have done another test and can confirm that when running the `make all` command as `sudo` it puts the `.vbox` file in the above mentioned path `/var/root/VirtualBox VMs`

I guess the `$HOME` variable is being filled with the root home upon issuing the `make ...` command preceding with `sudo`

**Comment by HigH-HawK** [comment] 2019-04-17 08:33
Hey Alex, I had a little thought about the `$HOME` issue. Would it be possible to create some sort of HOME variable right at the beginning of the script and filling this variable with the User HOME?

Example: `readonly HOME=$HOME`

Since it is `readonly` it should not be possible for the script, to override this variable in case `sudo` needs to be used and the `*.vbox` files will still be saved in the right User HOME? My understanding of the `readonly` property could however be wrong at this time. It's just an idea to prevent the root HOME from being used.

**Comment by AlexanderWillner** [comment] 2019-04-17 09:58
Actually, running a command via ```sudo``` should not change the ```$HOME``` variable, only when the parameter ```-H``` has been used. This is why the script works for me and many others, but not for those of you that are in this thread. Not sure yet what is special about your environment.

**Comment by 708145h** [comment] 2019-06-30 07:11
how can I fix my vm not showing in list? im not very technical

**Comment by AlexanderWillner** [comment] 2020-07-19 17:05
Closing stalled issues.

**Closed by AlexanderWillner** 2020-07-19 17:05 UTC
Labels: bug
