### ISSUE TITLE
Install macOS - Continue - button is disabled

### ISSUE THREAD

**Issue by zoechi** [AlexanderWillner/runMacOSinVirtualBox#87] opened 2019-11-07 16:41 UTC
Host macOS Catalina on a MacBook Pro
Guest macOS Catalina

`make all` creates the VM and boots the installation, but after selecting the language
the screen "Mac OS Utilities" is shown.
I can select "Install macOS" (or any other entry) but can't continue because the "Continue" button is disabled.

**Expected behavior**
Being able to continue installation

**Additional context**
 - log file

[runMacOSVirtualbox.log](https://github.com/AlexanderWillner/runMacOSinVirtualBox/files/3820693/runMacOSVirtualbox.log)

 - screen shot
![image](https://user-images.githubusercontent.com/405837/68407981-c45d9680-0184-11ea-95cc-0ecc4edb4cbf.png)

**Comment by zoechi** [comment] 2019-11-07 16:41
Shutting down and starting the VM again resulted in the same behaviour.

**Comment by jcdubiel** [comment] 2020-04-02 02:27
Any movement on this?  For me the Continue button is initially selectable.  It grays out when you click on it and then nothing happens.  Not the same behavior when installing Mojave.

**Comment by AlexanderWillner** [comment] 2020-07-19 17:22
Thanks for the feedback. However, couldn't reproduce this issue. Maybe fixed by now. Closing stalled issue.

**Closed by AlexanderWillner** 2020-07-19 17:22 UTC

**Comment by zoechi** [comment] 2020-07-20 05:14
Thanks for looking into it. I'll try again.
